# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/skill-challenge',
                'doc_host': 'https://Jan-David-Black.github.io',
                'git_url': 'https://github.com/Jan-David-Black/skill-challenge',
                'lib_path': 'skill_challenge'},
  'syms': { 'skill_challenge.core': {'skill_challenge.core.foo': ('singlemode.html#foo', 'skill_challenge/core.py')},
            'skill_challenge.util': { 'skill_challenge.util.TE_pol_fraction': ('util.html#te_pol_fraction', 'skill_challenge/util.py'),
                                      'skill_challenge.util.cCrossSection': ('util.html#ccrosssection', 'skill_challenge/util.py'),
                                      'skill_challenge.util.cCrossSection.__hash__': ( 'util.html#ccrosssection.__hash__',
                                                                                       'skill_challenge/util.py'),
                                      'skill_challenge.util.cMode': ('util.html#cmode', 'skill_challenge/util.py'),
                                      'skill_challenge.util.cMode.__hash__': ('util.html#cmode.__hash__', 'skill_challenge/util.py'),
                                      'skill_challenge.util.cMode.getMode': ('util.html#cmode.getmode', 'skill_challenge/util.py'),
                                      'skill_challenge.util.cachedComputeModes': ( 'util.html#cachedcomputemodes',
                                                                                   'skill_challenge/util.py'),
                                      'skill_challenge.util.dict_to_hash': ('util.html#dict_to_hash', 'skill_challenge/util.py'),
                                      'skill_challenge.util.inner': ('util.html#inner', 'skill_challenge/util.py')}}}
