# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/skill-challenge',
                'doc_host': 'https://Jan-David-Black.github.io',
                'git_url': 'https://github.com/Jan-David-Black/skill-challenge',
                'lib_path': 'skill_challenge'},
  'syms': {'skill_challenge.core': {'skill_challenge.core.foo': ('core.html#foo', 'skill_challenge/core.py')}}}
