# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_util.ipynb.

# %% auto 0
__all__ = ['PDK', 'nm', 'TE_pol_fraction']

# %% ../nbs/00_util.ipynb 3
# util functions go here
import numpy as np
import gdsfactory.simulation.gtidy3d as gt
import matplotlib.pyplot as plt
import gdsfactory as gf

gf.config.rich_output()
PDK = gf.generic_tech.get_generic_pdk()
PDK.activate()

nm = 1e-3

# %% ../nbs/00_util.ipynb 4
def TE_pol_fraction(self):
        """TE polarization fraction according to Lumericals definition. (assuming a regular mesh)"""
        Ex_sq = np.abs(self._data["Ex"])**2
        Ey_sq = np.abs(self._data["Ey"])**2
        
        return np.sum(Ex_sq, axis=(0,1))/np.sum(Ex_sq+Ey_sq, axis=(0,1))

setattr(gt.modes.Waveguide, 'TE_pol_fraction', property(TE_pol_fraction))
